CREATE TABLE IF NOT EXISTS hits
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app_name VARCHAR(50)                                          NOT NULL,
    uri      VARCHAR(250)                                         NOT NULL,
    ip       VARCHAR(50)                                          NOT NULL,
    date     TIMESTAMP WITHOUT TIME ZONE                          NOT NULL
);