CREATE TABLE IF NOT EXISTS hits
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app_name  VARCHAR(255)                                         NOT NULL,
    uri       VARCHAR(255)                                         NOT NULL,
    ip        VARCHAR(255)                                         NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE                          NOT NULL
);
